### ISSUE TITLE
update bundled tslint

### ISSUE THREAD

**Issue by stas-vilchik** [SonarSource/SonarTS#275]
Update at least to 5.4.3 to fix #267 

https://github.com/palantir/tslint/blob/master/CHANGELOG.md#v543

**Comment by vilchik-elena** [comment]
Add following new rules to SonarTS SQ plugin:
- [ ] [no-this-assignment](https://palantir.github.io/tslint/rules/no-this-assignment/) **Stas, WDYT?**
- [ ] [no-duplicate-imports](https://palantir.github.io/tslint/rules/no-duplicate-imports/) RSPEC-?
- [ ] [no-submodule-imports](https://palantir.github.io/tslint/rules/no-submodule-imports/) **Stas, WDYT?**
- [ ] [no-return-await](https://palantir.github.io/tslint/rules/no-return-await/) **Stas, WDYT?**
- [ ] [ban-comma-operator](https://palantir.github.io/tslint/rules/ban-comma-operator/) RSPEC-878 - tslint doesn't exclude for stmts
- [ ] [no-implicit-dependencies](https://palantir.github.io/tslint/rules/no-implicit-dependencies/) **Stas, WDYT?**


- [ ] [typeof-compare](https://palantir.github.io/tslint/rules/typeof-compare/) is deprecated in tslint 5.8 because typescript already does that check
