### ISSUE TITLE
Add property for TypeScript configuration file name

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarTS#354]
Mentioned in #215

**Comment by vilchik-elena** [comment]
@dantran Hi! In #215 you mentioned that your configuration file has different from `tsconfig.json` name. Could you explain the reason for that? Looks like many tools (including typescript compiler and language service in IDEs) rely on this convention

**Comment by dantran** [comment]
@vilchik-elena, my source tree has multiple app, each has its own tsconfig-xxx file.

**Comment by thedayzombiedreamer** [comment]
@vilchik-elena Hi, can you tell me the status of this issue? ;D
I'm really long for feature for customizing the `tsconfig.json`.
In my case, my project needs separated tsconfig file for server and front.

**Comment by vilchik-elena** [comment]
@thedayzombiedreamer Thanks for reaching us out! In fact, the matter is not about feature implementation but about "do we really need it"? Our main concern is that having not default config name breaks ability of IDE to correctly compile your code
Anyway we will probably reconsider it in next sprint (unfortunately no dates yet)

**Comment by Smenus** [comment]
@vilchik-elena Hi, just wondering if there's any news on this.
We have two tsconfig files, one that compiles our tests (tsconfig.json) and one that excludes them (tsconfig-notests.json). This is so that our IDE reports errors in them, but while we're running webpack and developing, making changes in our source that break our tests doesn't stop our webpack build.

Is the only way to exclude test files via excluding them in the tsconfig? It seems the standard Analysis Scope settings don't work for me.
