### ISSUE TITLE
SonarTS should fail fast when "node" executable is not available or is not the expected version

### ISSUE THREAD

**Issue by agigleux** [SonarSource/SonarTS#644]
While running my SonarQube Scanner, I expect my code scan to fail fast when I don't have any "node" executable installed or if the version installed is not the correct one.
With SonarTS 1.5+, I have an ERROR message but the scan is going until the end. If I don't look carefully at the logs, I will not see something is wrong in the configuration.

When there is no "node" executable, I expect:
- ERROR: "No 'node' executable was found; no TypeScript file will be analyzed."
- Java Exception

When the version of "node" is not the expected one (=> 6):
- ERROR: "The 'node' version installed is not the expected one; version 6+ is expected."
- Java Exception

**Comment by hosszubalazs** [comment]
Hey @vilchik-elena !

I ask you to reconsider this change. This change causes problems on projects where:
- Sonar is in use for some languages
- there is TypeScript code
- Sonar is not used for TypeScript analysis

This change means projects like this will start breaking. We use the same Sonar instance for multiple projects, with a lot of different setups.
If this breaking behaviour could be configured with a property, even if the default stays as-is, that would already be a workable solution. Do you see this as possible? 
I know the topic of build breaking is usually debated. :) I feel like it would be more consistent from your side to not break by default. 
https://blog.sonarsource.com/why-you-shouldnt-use-build-breaker/ 

Cheers and thanks for considering,
Balázs

**Comment by saberduck** [comment]
@hosszubalazs recommended solution in such case is to exclude TypeScript files from the analysis using `sonar.exclusions` property, which accepts wildcards so following should work '**/*.ts'  

Would that work for you?

**Comment by hosszubalazs** [comment]
Hey @saberduck ,

Thanks for the quick answer!

sonar.exclusions is a bit messy. We need a safe solution, so exclusions needs to be set by default. In turn, projects that do need the analysis will need to add a limited exclusion property, which looks strange in the end. I'd be happier with my suggestion, but if nothing else this can work.

To shine a different light on this topic, I'm missing a possibility to enable/disable languages on certain projects. In Sonar if a plugin is installed, the language is implicitly enabled everywhere. Using an empty profile ( 0 rules) by default was an effective way to control this. In the past this could work, since project analysis in itself never broke.
The TypeScript plugin breaks this concept. It would be super cool, both for TypeScript and in general, to skip analysis altogether for a certain language if there are 0 rules applied. This would also help solve my current issue, if this is possible at all.

**Comment by vilchik-elena** [comment]
@hosszubalazs similar to exclusions workaround: redefine ts suffixes to something unmatching on the projects where you would like to ignore ts. 
```
sonar.typescript.file.suffixes=_
```

**Comment by dokaspar** [comment]
Hi, 

Please consider that it used to be possible with the previous version of SonarTS (1.6) to have an empty TS profile, but have Sonar upload all the TypeScript code including coverage (lcov) information. This was a nice way to browse the code and see line-by-line code coverage. Excluding *.ts sources or changing the suffix kind of destroys this feature....

I understand that SonarTS depends on TSlint, which depends on node/npm. But running in an environment without node/npm pre-installed on the build hosts, a Sonar analysis shouldn't "fail fast" but  preferably skip TS and continue with the analysis of remaining languages...

Cheers,
Dominik

**Comment by saberduck** [comment]
I understand that this might look like we haven't thought this through, but I assure you that we did. What we were facing before, were complaints from customers that our analyzer is not working, because we weren't raising any issues. And this was because the analysis was failing gracefully. This would mean that code with blocking issues would pass quality gate. We believe that this is more important and not acceptable.

This behavior is consistent with other plugins. Java code analysis will also fail when JDK is not available.

I somehow don't understand the use case to have TypeScript code on CI environment and not having NodeJS runtime. How is the code compiled then? Maybe if you can explain how your CI pipeline is working we can find some solution to satisfy this usecase.

**Comment by GuiF007** [comment]
Hi !

Is there a way to use a build-in NodeJS instead of a global NodeJS ? I don't want to use a global NodeJS on my machine. On my java project, I use the com.github.eirslett.frontend-maven-plugin to install Node and Yarn, in order to use it only on my project...

It seems on 1.7, analysis crashes, not in 1.6...

**Comment by saberduck** [comment]
@GuiF007 it is possible to use nodejs provided by gradle plugin, you just need to set `sonar.typescript.node` property to the location of NodeJS executable

**Comment by GuiF007** [comment]
> Also 1.6 version was very likely not working properly and files were simply skipped.

Yeap we noticed that on ours pipeline execution, we had errors, but only an error, not a crash.
I will have a try with this `sonar.typescript.node`, thank you !
