### ISSUE TITLE
Merge no-dead-store and no-element-overwrite?

### ISSUE THREAD

**Issue by ethanresnick** [SonarSource/SonarTS#648]
**I want to request a feature.**
See title. Am I right in thinking that no-element-overwrite is just a specific case of no-dead-store? If so, should these rules be merged?

**Comment by vilchik-elena** [comment]
I see your point. But still we prefer to keep these two rules separated due to several nuances. `no-dead-store` raises issues on local variables only, so we can be sure about all writes and reads to them. So its implementation is much more advanced, it's based on control flow. In the same time rewriting the same element might have some semantics (if there is a setter), so somebody might want to disable it.
Anyway, it's not written in the stone, and maybe indeed we will see value in merging 2 rules one day. For now I think it's doesn't worth it. In any case, thanks for your feedback!
