### ISSUE TITLE
Add external rule descriptions for tslint-sonarts plugin

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/SonarTS#684]
And may be some other popular tslint plugins

**Comment by christophka** [comment]
Will this allow me to see linting problems in SonarQube that were saved to a tslint report using the tslint CLI for rules defined by a plugin (e.g. tslint-microsoft-contrib)?
Because i ran into the problem that only the rules defined by tslint itself are visible in SonarQube, but no rules from any plugins (in my case **no-suspicious-comment** from **tslint-microsoft-contrib** and **no-commented-code** from **tslint-sonarts**). And otherwise i would create another issue.

It would be nice to have a generic way of supporting rules from any plugin - especially if it comes to writing my own rules

**Comment by vilchik-elena** [comment]
@christophka No, this ticket is only about rule descriptions. 
Please create a ticket

**Comment by christophka** [comment]
Alright, i did create it: #729
