### ISSUE TITLE
Improve logging for lcov parser when coverage report is inconsistent 

### ISSUE THREAD

**Issue by SeyVaneerdewegh** [SonarSource/SonarTS#776]
**I want to request a feature.**
Make the logging of problems with the parsing of LCOV consistent with SonarJS 

In SonarJS the parser was changed so it will log problems with level _[DEBUG]_.
In SonarTS this is not (yet) implemented and it will log problems with level _[WARNING]_.

**For SonarJS**
Originally reported: https://github.com/SonarSource/SonarJS/issues/942
Addressed in: https://github.com/SonarSource/SonarJS/pull/1018

**Comment by koningskristof** [comment]
+1, we have 65k lines of LCOV warnings in our logs

**Comment by vilchik-elena** [comment]
+1 as well

Still I'm curious what are these 65k warnings you are having @koningskristof. Could you share some details?

**Comment by koningskristof** [comment]
Yes, it are even more I see...
Well we have this warning: 'Problem during processing LCOV report: can't save DA data for line xxx ' 137286 times in our logs, for 1 build. Which leads to log files of 60 MB, oops ...
We haven't been able to solve this, but we are sure it has something to do with our coverage reports of our unit tests. 
On the other hand, we have a code coverage in Sonar, which is very important. But now we have hard times to debug our logs, when something goes wrong. Because a 60MB build log is hard to read :/

**Comment by vilchik-elena** [comment]
@koningskristof ok, I see. 

So you mean even with 137k of warnings (and thus with ~137k TS lines without coverage in SQ) coverage info displayed in SQ is still valuable for you?

**Comment by koningskristof** [comment]
You are right, that is questionable ;-) But by some way, to be investigated, we have coverage for those line in Sonar. However, for me that is another working point.

**Comment by anneleenscholts** [comment]
+1

**Comment by mwarrens** [comment]
+1

**Comment by koendendas** [comment]
+1
