### ISSUE TITLE
exclude _prefix from no-dead-store

### ISSUE THREAD

**Issue by ssube** [SonarSource/SonarTS#781]
I'm looking for a way to exclude some unused variables from the `no-dead-store` rule. Particularly when destructuring, it can be helpful to declare a variable that will never be read:

```typescript
const { _removed, ...retained } = object;

const [_, foo, bar] = /(a)(b)/.exec('ab');
```

The [tslint `variable-name` rule](https://palantir.github.io/tslint/rules/variable-name/) has an `"allow-leading-underscore"` option (and a few others). Would something like that make sense and/or a PR be accepted for this rule?

**Comment by vilchik-elena** [comment]
for object destructuring all vars are ignored by this rule already since version 1.4 (see https://github.com/SonarSource/SonarTS/issues/402)

for array destructuring you can just omit var name if you don't need it
```
const [, foo, bar] = /(a)(b)/.exec('ab');
```

**Comment by ssube** [comment]
Great news on the object side, however loose commas are not a viable option. Skipping more than one element quickly leads to code like `[, , , foo, , , bar]` and becomes impossible to maintain. Is there another way to make the `no-dead-store` usable with array destructuring?

**Comment by vilchik-elena** [comment]
Indeed, looks like in case of `[, , , foo, , , bar]` it's better to use indexes (`arr[3]` and `arr[6]`).
Another idea is to use comments `[/*first*/, second, /*third*/, forth]`. 
Otherwise, I don't think it makes sense to ignore all unused vars from array destructuring. It will bring a lot of FN, while they could be avoided.
